### ISSUE TITLE
train process

### ISSUE THREAD

**Issue by 738654805** [simonhessner/masters-thesis-final#1]
Thank you for sharing your code.
Can you provide your train process in readme.

**Comment by simonhessner** [comment]
Unfortunately I am too busy to provide an extensive explanation, sorry. But since I used `argparse` for all training scripts and provided help texts for all options, it should be possible to use with a bit of trying.

For example, in `pe_hourglass` there is the `main.py` file which is responsible for training an hourglass. It has four parameters:

- config file (generated using `config_generator/make_configs.py`. There are also templates in that folder)
- output directory
- data (path to h5 file with all the training and test images)
- GPU ID

If you want to perform a bigger grid search, you can use `trainer.py` in the root directory.
